import type { Metadata } from "next";
import { Geist, Geist_Mono, IBM_Plex_Sans_Thai } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
const ibmSans = IBM_Plex_Sans_Thai({
  variable: "--font-ibm-sans",
  subsets: ["thai", "latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"]
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        // className={`${geistSans.variable} ${geistMono.variable} ${ibmSans.variable} antialiased`}
        className={`${ibmSans.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
